/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const OrganizationType = IDL.Variant({
  'FPO' : IDL.Null,
  'other' : IDL.Null,
  'buyer' : IDL.Null,
  'farmer' : IDL.Null,
  'investor' : IDL.Null,
});
export const ContactSubmission = IDL.Record({
  'id' : IDL.Nat,
  'orgType' : OrganizationType,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'deleteSubmission' : IDL.Func([IDL.Nat], [], []),
  'getAllSubmissions' : IDL.Func([], [IDL.Vec(ContactSubmission)], ['query']),
  'getSubmission' : IDL.Func([IDL.Nat], [ContactSubmission], ['query']),
  'getVisitCount' : IDL.Func([], [IDL.Nat], ['query']),
  'incrementVisitCount' : IDL.Func([], [], []),
  'submitContact' : IDL.Func(
      [IDL.Text, OrganizationType, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const OrganizationType = IDL.Variant({
    'FPO' : IDL.Null,
    'other' : IDL.Null,
    'buyer' : IDL.Null,
    'farmer' : IDL.Null,
    'investor' : IDL.Null,
  });
  const ContactSubmission = IDL.Record({
    'id' : IDL.Nat,
    'orgType' : OrganizationType,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'deleteSubmission' : IDL.Func([IDL.Nat], [], []),
    'getAllSubmissions' : IDL.Func([], [IDL.Vec(ContactSubmission)], ['query']),
    'getSubmission' : IDL.Func([IDL.Nat], [ContactSubmission], ['query']),
    'getVisitCount' : IDL.Func([], [IDL.Nat], ['query']),
    'incrementVisitCount' : IDL.Func([], [], []),
    'submitContact' : IDL.Func(
        [IDL.Text, OrganizationType, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };